# general settings
settings:
  mapper: ["bwa","bowtie2"]
  threads: 1
  seqdir: "/media/box2/Data/Joanna/trimmed_fastq/Tcell/"
  resdir: "Tcell/"  
  javaopts: "-Xmx5g -Djava.io.tmpdir=`pwd`/tmp"

# information on folder/file structure for the samples
sampleinfo:
  file: "sampleinfo.csv"
  outfmt: "{sample}{extension}"
  mergefmt: "{experiment}/{sample}/{sample}"

# genome and other reference files, where symlinks will be created
ref:
  genome: "indexfiles/human_g1k_v37_decoy.fasta"
  mills: "indexfiles/Mills_and_1000G_gold_standard.indels.b37.vcf"
  kgindels: "indexfiles/1000G_phase1.indels.b37.vcf"

bundle:
  genome: "/media/box2/reference_assemblies/bundle/2.8/b37/from_pall/human_g1k_v37_decoy.fasta"
  mills: "/media/box2/reference_assemblies/bundle/2.8/b37/from_pall/Mills_and_1000G_gold_standard.indels.b37.vcf"
  kgindels: "/media/box2/reference_assemblies/bundle/2.8/b37/from_pall/1000G_phase1.indels.b37.vcf"

