# simulation settings

# OBS! ncell and number of cells indicated in phyl_tree needs to be the same!
#  
#  phyl_tree: { 0:[0,1,2,3,4], 1:[5,6,7,8,9]}
#  f_SNV: [0,1]
#  f_EAL: [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
#  f_ADO: [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]


simulation:
  ncell: 20
  phyl_tree: { 0:[0,1,2,3,4,5,6,7,8,9], 1:[10,11,12,13,14,15,16,17,18,19] }
  f_SNV: [1]
  f_EAL: [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
  f_ADO: [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
  use_freq: False
  locus_count_limit: 20
  fixed: True
  path: /media/box2/Experiments/Joanna/Snake_analys/j_frisen_1602/simulation/script
  sites_file: /media/box2/Experiments/Joanna/Simulering/data/final_sites/sites_for_simulation.tsv
  counts_file: /media/box2/Experiments/Joanna/Simulering/data/coverage-fil181108/coverage_in_gSNVs.txt
  lc_pickle: data/common/locusCounts.pkl
  hetf: /media/box2/Experiments/Joanna/Simulering/data/bam_files/female_good_bulk.reAligned.bwa.bam
  homf: /media/box2/Experiments/Joanna/Simulering/data/bam_files/FibBulk.reAligned.bwa.bam


###########################################
# general settings
settings:
  javaopts: "-Xmx5g -Djava.io.tmpdir=`pwd`/tmp"
  javaopts10: "-Xmx32g -Djava.io.tmpdir=`pwd`/tmp"  
  reference_original: "/media/box2/reference_assemblies/bundle/2.8/b37/from_pall/human_g1k_v37_decoy.fasta"
  reference: data/ref/human_g1k_v37_decoy.fasta
  ref_dict: data/ref/human_g1k_v37_decoy.dict
  interval_dist: 10000

###########################################
# conbase

conbase:
  path:  /media/box2/Experiments/Joanna/Snake_analys/j_frisen_1602/programs/conbase/bin/Main.py
  sites_file: "/media/box2/Experiments/Joanna/Simulering/data/conbase_snp_list.tsv"
  threads: 2


###########################################
# monvar:

monovar:
  path: /media/box2/Experiments/Joanna/Snake_analys/j_frisen_1602/programs/monovar/src
  conda: monovar
  threads: 2
  mpileup_settings: "-BQ0 -d10000 -q 40"
  monovar_settings: "-p 0.002 -a 0.2 -t 0.05"

###########################################
# sccaller
sccaller:
  conda: sccaller
  dbsnp: /media/box2/reference_assemblies/bundle/2.8/b37/from_pall/dbsnp_138.b37.vcf
  merge_script: /media/box2/Experiments/Joanna/Snake_analys/j_frisen_1602/pipeline_simulation/scripts/merge_sccaller_output.py
  
###########################################
# parsing

parsing:
  path: /media/box2/Experiments/Joanna/Snake_analys/j_frisen_1602/pipeline_simulation/scripts/parse_simulation_data.py
  path_w_lira: /media/box2/Experiments/Joanna/Snake_analys/j_frisen_1602/pipeline_simulation/scripts/parse_simulation_data_w_lira.py
  path_sum: /media/box2/Experiments/Joanna/Snake_analys/j_frisen_1602/pipeline_simulation/scripts/summarize_simulation_stats.py
  path_sum2: /media/box2/Experiments/Joanna/Snake_analys/j_frisen_1602/pipeline_simulation/scripts/summarize_simulation_stats_w_scc.py    
  monovar_dp: 5
  monovar_gq: 0
  monovar_nmut: 0


###########################################
# lira:

lira:
  config_template: /media/box2/Experiments/Joanna/LiRA/config_pipeline.yaml
  snakefile1: /media/box2/Experiments/Joanna/Snake_analys/j_frisen_1602/pipeline_lira/Snakefile
  snakefile2: /media/box2/Experiments/Joanna/Snake_analys/j_frisen_1602/pipeline_lira/snakefile_non_dynamic.smk
  gatk_conda: GATK
  gatk_settings: "--emitRefConfidence GVCF --variant_index_type LINEAR --variant_index_parameter 128000"
  gatk_threads: 5
  gatk_threads_use: 5 # need to submit with fewer cores than the rule permits to not get memory error!
  snake_conda_path: /media/box2/Experiments/Joanna/bin/miniconda3/envs/snake2/bin
  lira_conda_path: /media/box2/Experiments/Joanna/bin/miniconda3/envs/LiRA/bin
  lira_dir: /media/box2/Experiments/Joanna/LiRA/LiRA_sim
  split_threads: 21
  varcall_threads: 21  
  chromosomes: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21,22]
  merge_script: /media/box2/Experiments/Joanna/Snake_analys/j_frisen_1602/pipeline_simulation/scripts/merge_lira_output.py  
# no sites on chr19, need to remove that one!
