import os,sys

configfile: "config_pipeline.yaml"
 
include: "rules/simulate.smk"
include: "rules/utils.smk"
include: "rules/conbase.smk"
include: "rules/monovar.smk"
include: "rules/lira_allregions.smk"
include: "rules/gatk_allregions.smk"
include: "rules/summarize.smk"


# make targets for split:
SIM_TARGETS = expand( "data/sim_snv{f_SNV}_eal{f_EAL}_ado{f_ADO}/bams/sim.chk", f_SNV = config["simulation"]["f_SNV"],f_EAL = config["simulation"]["f_EAL"],f_ADO = config["simulation"]["f_ADO"])

CONBASE_TARGETS = expand( "data/sim_snv{f_SNV}_eal{f_EAL}_ado{f_ADO}/conbase/conbase_results.html", f_SNV = config["simulation"]["f_SNV"],f_EAL = config["simulation"]["f_EAL"],f_ADO = config["simulation"]["f_ADO"])

MONOVAR_TARGETS = expand( "data/sim_snv{f_SNV}_eal{f_EAL}_ado{f_ADO}/monovar/monovar_output.vcf", f_SNV = config["simulation"]["f_SNV"],f_EAL = config["simulation"]["f_EAL"],f_ADO = config["simulation"]["f_ADO"])

LIRA_TARGETS = expand( "data/sim_snv{f_SNV}_eal{f_EAL}_ado{f_ADO}/lira/lira_output/all_cells.chk", f_SNV = config["simulation"]["f_SNV"],f_EAL = config["simulation"]["f_EAL"],f_ADO = config["simulation"]["f_ADO"])

rule all_sim:
    input:
        sim_data = SIM_TARGETS,
        
rule all_conbase:
    input: CONBASE_TARGETS

rule all_lira:
    input: LIRA_TARGETS

rule all:
    input: CONBASE_TARGETS + MONOVAR_TARGETS
           
           

        
        

