import os,sys

configfile: "config_pipeline.yaml"
 
include: "rules/simulate.smk"
include: "rules/utils.smk"
include: "rules/conbase.smk"
include: "rules/monovar.smk"
#include: "rules/lira_allregions.smk"
#include: "rules/gatk_allregions.smk"
include: "rules/gatk.smk"
include: "rules/lira.smk"
include: "rules/sccaller.smk"
include: "rules/summarize.smk"


# make targets for split:
SIM_TARGETS = expand( "data/sim_snv{f_SNV}_eal{f_EAL}_ado{f_ADO}/bams/sim.chk", f_SNV = config["simulation"]["f_SNV"],f_EAL = config["simulation"]["f_EAL"],f_ADO = config["simulation"]["f_ADO"])

CONBASE_TARGETS = expand( "data/sim_snv{f_SNV}_eal{f_EAL}_ado{f_ADO}/conbase/conbase_results.html", f_SNV = config["simulation"]["f_SNV"],f_EAL = config["simulation"]["f_EAL"],f_ADO = config["simulation"]["f_ADO"])

MONOVAR_TARGETS = expand( "data/sim_snv{f_SNV}_eal{f_EAL}_ado{f_ADO}/monovar/monovar_output.vcf", f_SNV = config["simulation"]["f_SNV"],f_EAL = config["simulation"]["f_EAL"],f_ADO = config["simulation"]["f_ADO"])

LIRA_TARGETS = expand( "data/sim_snv{f_SNV}_eal{f_EAL}_ado{f_ADO}/lira/lira_output/all_cells.chk", f_SNV = config["simulation"]["f_SNV"],f_EAL = config["simulation"]["f_EAL"],f_ADO = config["simulation"]["f_ADO"])
GATK_TARGETS = expand( "data/sim_snv{f_SNV}_eal{f_EAL}_ado{f_ADO}/lira/vcf/all.vcf.gz.tbi", f_SNV = config["simulation"]["f_SNV"],f_EAL = config["simulation"]["f_EAL"],f_ADO = config["simulation"]["f_ADO"])

SCC_TARGETS = expand("data/sim_snv{f_SNV}_eal{f_EAL}_ado{f_ADO}/sccaller/all_cells.chk", f_SNV = config["simulation"]["f_SNV"],f_EAL = config["simulation"]["f_EAL"],f_ADO = config["simulation"]["f_ADO"])

rule all_sim:
    input: SIM_TARGETS
        
rule all_conbase:
    input: CONBASE_TARGETS

rule all_monovar:
    input: MONOVAR_TARGETS
           
rule all_lira:
    input: LIRA_TARGETS

rule all_gatk:
    input: GATK_TARGETS
           
rule all_sccaller:
    input: SCC_TARGETS

rule merge_sccaller:
    input: expand("data/sim_snv{f_SNV}_eal{f_EAL}_ado{f_ADO}/sccaller/all_cells_stats.csv", f_SNV = config["simulation"]["f_SNV"],f_EAL = config["simulation"]["f_EAL"],f_ADO = config["simulation"]["f_ADO"])

rule all:
    input: CONBASE_TARGETS + MONOVAR_TARGETS + SCC_TARGETS
           
           



## Extra to run plink chk before anything else is run:
PLINK_TARGETS = expand( "data/sim_snv{f_SNV}_eal{f_EAL}_ado{f_ADO}/lira/lira_output/bulk/progress/all_chrom_plink.chk", f_SNV = config["simulation"]["f_SNV"],f_EAL = config["simulation"]["f_EAL"],f_ADO = config["simulation"]["f_ADO"])

rule all_plink_bulk:
    input: PLINK_TARGETS

